import './globals.css'
import type { Metadata } from 'next'
import Provider from './Providers'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-light-e dark:bg-dark-2 font-inter'>
          <Provider>
            {children}
          </Provider>
        
      </body>
        
    </html>
  )
}
